### ISSUE TITLE
Custom HUD part 1

### ISSUE THREAD

**Issue by NikolaiVChr** [swampmo/Jaguar#26]
List of things todo to make the HUD more custom to Jaguar:

Seems the KIAS and ALT follows the FPM up and down in HUD and is located above it.
The 04 and 05 below it also follows it and is the heading scale.
A small 'L' is displayed just above the FPM when too low for bomb arming time it seems.
The HUD had CCRP also. And azimuth line rotated with roll.
CCIP had a bomb fall line from FPM to pipper.
An arch on the heading scale is bug.
Scale on right side is vertical speed.
What is the left scale about? (most likely AoA)
Radar alt should have R in front instead of H. And is displayed instead of regular alt, so not at same time.
HUD crossed out when pull up cue appears.

Swamp requests bigger fonts than usual and less bright HUD color.

![image](https://user-images.githubusercontent.com/3764194/73705164-70b40800-46f5-11ea-928d-909c93c76abb.png)

![image](https://user-images.githubusercontent.com/3764194/73705223-8b867c80-46f5-11ea-8d15-36d6762046a6.png)

![image](https://user-images.githubusercontent.com/3764194/73705423-2e3efb00-46f6-11ea-9e42-47e6c71ee79e.png)

**Comment by swampmo** [comment]
I saw a F-15 HUD with TIALD, apparently it was used in the HUD only in this plane I'm not sure. I don know some GR.1 planes were outfitted with TIALD, some got as updated HUDand  5" x 5' look down MFD others did not get the MFD. This would mean the only way the TIALD could work for the ones without the MFD which served other purposes such as GPS, etc. would be through the HUD, I posted it somewhere in the Discord server the other day. That would be the answer for marking their own laser guided bombs.

**Comment by swampmo** [comment]
![image](https://user-images.githubusercontent.com/16342224/73989586-e85b8000-490b-11ea-8cea-e3f4f7827886.png)

**Comment by swampmo** [comment]
Above is the GR.1 HUD while dropping dumb bombs and laser guided bombs. In one of the above images it shows the pip for guns and Rockets only but I'm not sure if that was from one of the proposed systems in one of our documents. Of course for the above image to work we would have to some how target object. I'm not sure how we can do this if adding GPS is not accurate. Using the TIALD pod with the HUD this would be the same as earlier versions of laser guided targeting done in the F-16 and other planes in the past. The TIALD pod was used on an under wing pylon. above wing pods were ECM which I don't think we will bother with. As far as I know not even our F-16 has ECM.

**Comment by NikolaiVChr** [comment]
HUD WAS 664 system:
![image](https://user-images.githubusercontent.com/3764194/118998117-78023200-b989-11eb-8296-46f5c36f9319.png)

More Jaguar HUD info:
![image](https://user-images.githubusercontent.com/3764194/118999192-5a819800-b98a-11eb-92e0-7006fd182cf4.png)
![image](https://user-images.githubusercontent.com/3764194/118999282-6bcaa480-b98a-11eb-9dbf-fad0d535a336.png)
![image](https://user-images.githubusercontent.com/3764194/118999407-88ff7300-b98a-11eb-9c0e-87fe4bbabd4f.png)
![image](https://user-images.githubusercontent.com/3764194/118999620-b77d4e00-b98a-11eb-8fbb-62118f510ca7.png)
![image](https://user-images.githubusercontent.com/3764194/118999816-e267a200-b98a-11eb-8deb-6571938662fa.png)
![image](https://user-images.githubusercontent.com/3764194/118999872-ebf10a00-b98a-11eb-8caa-e407c70b71c1.png)
![image](https://user-images.githubusercontent.com/3764194/118999942-f7443580-b98a-11eb-807f-fac6c0125814.png)
![image](https://user-images.githubusercontent.com/3764194/119000004-03c88e00-b98b-11eb-91e2-28281e6b836e.png)

I am posting this here, to keep info about the HUD in one place. For future extension of its capabilities.
