### ISSUE TITLE
Add functionality and keys for GCI

### ISSUE THREAD

**Issue by vanosten** [swampmo/Jaguar#43]
See e.g. MiG-21bis\Nasal\gci-listener.nas and MiG-21bis\Systems\keyboard.xml.

MP porps used needs to be added to oprf-assets\gci-radar\Nasal\gci.nas

**Comment by Zaretto** [comment]
Pull request will be made shortly for oprf-assets\gci-radar\Nasal\gci.nas

**Comment by Zaretto** [comment]
@vanosten Please test this as it's not something that I'm familiar with.
