### ISSUE TITLE
Produce single model / texture for the cockpit interior

### ISSUE THREAD

**Issue by Zaretto** [swampmo/Jaguar#52]
Produce single model / texture for the cockpit interior

**Comment by swampmo** [comment]
I just saw this. My lack of navigating the website.

**Comment by Zaretto** [comment]
After some thought I've changed my mind and it is better that we don't do this for the FGaddon release; instead it can be done at some point later. There are a couple of reasons for this:

* There are minor improvements to the 3d model that are needed 
* improvement of the textures (labels etc); as when we merge the models that all share certain textures will end up using the same part of the texture atlas
* need to animate more of the cockpit
* need to review the instruments to ensure that the cockpit is correct for a GR1 (some version, possible after MLI)
